language: node_js
node_js:
- 12.1.0
git:
  depth: 9999999
dist: trusty
sudo: false
addons:
  ssh_known_hosts:
  - marc0.fr:4242
  - 51.77.202.182:4242
before_script:
  - cd webapp
  - sleep 15
  - cd ..
before_install:
  - openssl aes-256-cbc -K $encrypted_55da4941a3f7_key -iv $encrypted_55da4941a3f7_iv
    -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - cp .travis/deploy_rsa ~/.ssh/deploy_rsa
  - chmod 600 ~/.ssh/deploy_rsa
  - ssh-add ~/.ssh/deploy_rsa
deploy:
- provider: script
  script: ".travis/deploy.sh"
  on:
    branch: travis
