version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    restart: always
  client_web:
    build:
      context: ./webapp
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
      - "1341:80"
    depends_on:
      - server
    restart: always
